[package]
name = "gpio_control"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
rppal = "0.14"
dht-sensor = "0.1"
embedded-hal = { version = "0.2", features = ["unproven"] }
